stages:
  - test
  - build
  - deploy
unit-test:
  script: C:\Users\JSB\Desktop\Unity2019.3.13f1.lnk -batchmode -projectPath . -runTests -testPlatform editmode  -logFile -testResults ./unit-tests.xml
  stage: test
  tags:
    - unity
unity-build:
  script: "echo 'Building...'"
  stage: build
  tags:
    - unity
playstore:
  script: "echo 'Deploying...'"
  stage: deploy
  tags:
    - unity