public class Faction {

	enum Names{ 
		COALITION_OF_THE_BLACK_ANGELS,
		ENCLAVE_OF_TERRA,
		SYNDICATE,
		SWAMP_RUNNERS,
		NEW_FEDERALISTS,
		REGULATORS,
		THE_HIGHWAYMEN,
		THE_BROTHERHOOD,
		SONS_OF_NEPTUNE,
		SIGMA_CORPORATION
	};
}
